# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m

# Fabric Properties
minecraft_version=1.21.5
yarn_mappings=1.21.5+build.1
loader_version=0.19.3

# Mod Properties
mod_version=1.0.0
maven_group=com.supermodmenu
archives_base_name=supermodmenu

# Dependencies
fabric_version=0.128.2+1.21.5
